### ISSUE TITLE
Built-in optics

### ISSUE THREAD

**Issue by serras** [kutyel/optics.js#2]
One of the goals I think we should have is to make the programmer not type `lens` and `prism` over and over (I would even go further, maybe not even know what they mean!)

So I would like to suggest using names like `prop` and `ix` for the basic optics, instead of the longer `lensProp` and `lensIx` we have now. In combination with #1, we would have a syntax like the following:

```js
path(prop('this'), ix(2))
```

which reads quite good to my eyes.

(We could even build `path` in such a way that it automatically wraps with `prop` or `ix` if the argument is a string or a number, but I derail... But think about it)

What should be the default for properties and indices, lens or prism? My thoughts right now are about them being prisms, and then have a (unsafe if used wrong!) operation `sure` which turns a prism into a lens.

```js
path(sure(prop('this')), sure(ix(2)))
```

**Comment by kutyel** [comment]
I love the idea of having standalone functions for everything, pretty much Ramda style, but then we will not achieve the dot-chaining API we had in mind from the beginning? 🤔

**Comment by serras** [comment]
Standalone functions or dot style for operations, that’s what you have at
the end.

However, I am starting to think that the dot syntax to compose lenses is
not the best. Using `path`, which can take any amount of optics as
arguments, we have an easy way to compose optics, yet we keep a simple
style (and one similar to Swift’s keyPath)

**Comment by kutyel** [comment]
We agreed on having an API like:

```js
optic(sure(prop('this')), sure(ix(2)))
```

We (@serras and I) think it is cleaner and goes more into the style of Ramda rather than messing with prototypes.
