### ISSUE TITLE
Reach coverage 100%

### ISSUE THREAD

**Issue by kutyel** [kutyel/optics.js#26]
https://coveralls.io/builds/33716563/source?filename=src/errors.js

**Comment by bangn** [comment]
Hi @kutyel,

I would like to take a stab on it, is it ok?

Cheers,

**Comment by kutyel** [comment]
Sure, go ahead! 🚀

**Comment by kutyel** [comment]
According to coveralls, we need to test:

- `setIndex` in **functions.js**: https://coveralls.io/builds/33822419/source?filename=src/functions.js
- L78 of **Prism.js**: https://coveralls.io/builds/33822419/source?filename=src/Prism.js

@bangn in case it is of any help 😉

**Comment by kutyel** [comment]
Fixed by #31, thanks @bangn!
