### ISSUE TITLE
Prisms should use null or undefined?

### ISSUE THREAD

**Issue by serras** [kutyel/optics.js#3]
Right now prisms use `null` as the return value when something is not there. But should we use `undefined` instead? This would be coherent with what JS does with properties not available in objects.

```js
const o = { milk: 6 }
const p = o['pie']  // undefined
```

I am opening the issue to track the discussion.

**Comment by serras** [comment]
Right now I lean towards `undefined` for the reasons exposed above.

**Comment by kutyel** [comment]
I think undefined is JS' fallback behaviour when things are not defined (duh) but if you want to signal absence of a value, you should definitely use `null`. 😉
