### ISSUE TITLE
Something weird happens with boolean functions applied to `over`

### ISSUE THREAD

**Issue by kutyel** [kutyel/optics.js#33]
https://codesandbox.io/s/opticsjs-example-ov3ll?file=/src/index.js

**Comment by serras** [comment]
I am pretty sure it's something related to [this line](https://github.com/kutyel/optics.js/blob/master/src/Lens.js#L71), which reads:

```js
obj => (isNotFound(obj) ? notFound : obj[key] || notFound),
```

That `obj[key] || notFound` is there to cover the case in which `key` is not a property of `obj`, but it will also catch the case in which `obj[key]` is `false`, returning `notFound` then.

**Comment by kutyel** [comment]
this simple test does not pass:
```js
  test('over should work with boolean functions', () => {
    const neg = x => !x
    const liked = { liked: true }
    const lens = optic('liked')

    expect(view(lens, liked)).toBe(true)
    expect(view(lens, over(lens, neg, liked))).toBe(false)
  })
```
